name: AP Blake
favicon: null
layout_spectrum: 1
typography_spectrum: 0.34014075761660933
title: Under a Glass Bell
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#258095'
    - '#58abbd'
    - '#96d0dc'
    - '#065168'
  brandStrength: 0.8031215444207191
  lightness: 0.27225468936376274
  saturation: 0.8400290990248322
  rhythmicContrast: 0.759108904749155
purpose: []
