name: AP Blake
favicon: null
layout_spectrum: 1
typography_spectrum: 0.38108
title: Under a Glass Bell
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0e0e0e'
    - '#dcdbdc'
    - '#acacac'
    - '#464646'
    - '#818181'
  brandStrength: 0.25
  lightness: 0.27225468936376274
  saturation: 0.5
  rhythmicContrast: 0.759108904749155
purpose: []
